#if !defined(BECHAT_PROTO_MESSAGE_TAG_H_)
#define BECHAT_PROTO_MESSAGE_TAG_H_

// Reserved
#define BECHAT_TAG_RESERVED 0x0000U

// Session & Account
#define BECHAT_TAG_SIGNUP 0x0001U
#define BECHAT_TAG_LOGIN 0x0002U
#define BECHAT_TAG_LOGOUT 0x0003U
#define BECHAT_TAG_PING 0x0004U
#define BECHAT_TAG_REFRESH 0x0005U

// ChatMessage
#define BECHAT_TAG_SEND_MESSAGE 0x0101U
#define BECHAT_TAG_FETCH_HISTORY 0x0102U

// ChatInfo
#define BECHAT_TAG_GET_ONLINE_USERS 0x0201U

// ServerPush
#define BECHAT_TAG_SERVER_NOTICE 0x7001U
#define BECHAT_TAG_PUSH_MESSAGE 0x7101U
#define BECHAT_TAG_USER_JOINED 0x7201U
#define BECHAT_TAG_USER_LEFT 0x7202U

// Reserved 0x8XXX
#define BECHAT_TAG_RESERVED_0x8XXX 0x8000

#endif  // BECHAT_PROTO_MESSAGE_TAG_H_
