#if !defined(BECHAT_PROTO_MESSAGE_TAG_H_)
#define BECHAT_PROTO_MESSAGE_TAG_H_

// Reserved
#define BECHAT_TAG_RESERVED 0x0000

// Session & Account
#define BECHAT_TAG_SIGNUP 0x0001
#define BECHAT_TAG_LOGIN 0x0002
#define BECHAT_TAG_LOGOUT 0x0003
#define BECHAT_TAG_PING 0x0004

// ChatMessage
#define BECHAT_TAG_SEND_MESSAGE 0x0101
#define BECHAT_TAG_FETCH_HISTORY 0x0102

// ChatInfo
#define BECHAT_TAG_GET_ONLINE_USERS 0x0201

// ServerPush
#define BECHAT_TAG_SERVER_NOTICE 0x8001
#define BECHAT_TAG_PUSH_MESSAGE 0x8101
#define BECHAT_TAG_USER_JOINED 0x8201
#define BECHAT_TAG_USER_LEFT 0x8202

#endif  // BECHAT_PROTO_MESSAGE_TAG_H_
